export const tableData = [
  {
    sex: "0",
    name: "王楠",
    age: 37,
    height: "1.68",
    health: "0",
    education: "本科",
    job: "基金经理",
    maritalStatus: "0",
  },
  {
    sex: "1",
    name: "张三",
    age: 37,
    height: "1.68",
    health: "1",
    education: "本科",
    job: "基金经理",
    maritalStatus: "1",
  },
  {
    sex: "1",
    name: "李四",
    age: 37,
    height: "1.68",
    health: "1",
    education: "本科",
    job: "基金经理",
    maritalStatus: "0",
  },
  {
    sex: "1",
    name: "王五",
    age: 37,
    height: "1.68",
    health: "0",
    education: "本科",
    job: "基金经理",
    maritalStatus: "1",
  },
  {
    sex: "1",
    name: "马六",
    age: 37,
    height: "1.68",
    health: "1",
    education: "本科",
    job: "基金经理",
    maritalStatus: "0",
  },
  {
    sex: "0",
    name: "李楠",
    age: 37,
    height: "1.68",
    health: "0",
    education: "本科",
    job: "基金经理",
    maritalStatus: "1",
  },
  {
    sex: "1",
    name: "赵四",
    age: 37,
    height: "1.68",
    health: "1",
    education: "本科",
    job: "基金经理",
    maritalStatus: "1",
  },
  {
    sex: "1",
    name: "刘安",
    age: 37,
    height: "1.68",
    health: "1",
    education: "本科",
    job: "基金经理",
    maritalStatus: "1",
  },
  {
    sex: "0",
    name: "佩吉",
    age: 37,
    height: "1.68",
    health: "1",
    education: "本科",
    job: "基金经理",
    maritalStatus: "1",
  },
  {
    sex: "1",
    name: "华军",
    age: 37,
    height: "1.68",
    health: "1",
    education: "本科",
    job: "基金经理",
    maritalStatus: "1",
  },
  {
    sex: "1",
    name: "阮建安",
    age: 37,
    height: "1.68",
    health: "1",
    education: "本科",
    job: "基金经理",
    maritalStatus: "1",
  },
  {
    sex: "1",
    name: "柯楠",
    age: 37,
    height: "1.68",
    health: "1",
    education: "本科",
    job: "基金经理",
    maritalStatus: "1",
  },
  {
    sex: "1",
    name: "林国瑞",
    age: 37,
    height: "1.68",
    health: "1",
    education: "本科",
    job: "基金经理",
    maritalStatus: "1",
  },
  {
    sex: "1",
    name: "方强",
    age: 37,
    height: "1.68",
    health: "1",
    education: "本科",
    job: "基金经理",
    maritalStatus: "1",
  },
  {
    sex: "1",
    name: "宋清溪",
    age: 37,
    height: "1.68",
    health: "1",
    education: "本科",
    job: "基金经理",
    maritalStatus: "1",
  },
  {
    sex: "1",
    name: "刘竹庄",
    age: 37,
    height: "1.68",
    health: "1",
    education: "本科",
    job: "基金经理",
    maritalStatus: "1",
  },
  {
    sex: "1",
    name: "丁春秋",
    age: 37,
    height: "1.68",
    health: "0",
    education: "本科",
    job: "基金经理",
    maritalStatus: "1",
  },
  {
    sex: "1",
    name: "苏星河",
    age: 37,
    height: "1.68",
    health: "1",
    education: "本科",
    job: "基金经理",
    maritalStatus: "1",
  },
  {
    sex: "1",
    name: "段延庆",
    age: 37,
    height: "1.68",
    health: "1",
    education: "本科",
    job: "基金经理",
    maritalStatus: "1",
  },
  {
    sex: "1",
    name: "钟灵",
    age: 37,
    height: "1.68",
    health: "1",
    education: "本科",
    job: "基金经理",
    maritalStatus: "1",
  },
  {
    sex: "0",
    name: "王语嫣",
    age: 37,
    height: "1.68",
    health: "1",
    education: "本科",
    job: "基金经理",
    maritalStatus: "1",
  },
  {
    sex: "1",
    name: "出尘子",
    age: 37,
    height: "1.68",
    health: "1",
    education: "本科",
    job: "基金经理",
    maritalStatus: "1",
  },
  {
    sex: "1",
    name: "萧远山",
    age: 37,
    height: "1.68",
    health: "1",
    education: "本科",
    job: "基金经理",
    maritalStatus: "1",
  },
  {
    sex: "1",
    name: "段正淳",
    age: 37,
    height: "1.68",
    health: "1",
    education: "本科",
    job: "基金经理",
    maritalStatus: "1",
  },
];